name: Auto Merge dev to devkitasehat

on:
  push:
    branches:
      - dev

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: dev

    - name: Custom Action Using PAT
      run: |
        curl -H "Authorization: token ${{ secrets.TOKEN_PAT }}" https://api.github.com/

    - name: Configure Git
      run: |
        git config user.name 'marwandhiaurrahman'
        git config user.email 'marwandhiaurrahman@github.com'

    - name: Merge dev into devkitasehat
      run: |
        git fetch origin
        git checkout devkitasehat
        git merge origin/dev --strategy-option=ours --allow-unrelated-histories
        # Set remote URL with PAT for authentication
        git remote set-url origin https://x-access-token:${{ secrets.TOKEN_PAT }}@github.com/digitaaid/simrs.git
        git push origin devkitasehat
